#
# SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
# SPDX-License-Identifier: Apache-2.0
#
version = 1
SPDX-PackageName = "ml-workload-lib-for-vulkan"

[[annotations]]
path = "**/*.md"
SPDX-FileCopyrightText = "Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "docs/source/*.rst"
SPDX-FileCopyrightText = "Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "CONTRIBUTORS.txt"
SPDX-FileCopyrightText = "Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "patches/*.patch"
SPDX-FileCopyrightText = "Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>"
SPDX-License-Identifier = "Apache-2.0"
